services:
  web:
    build:
      context: docker/web
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www/html/
    ports:
      - 8000:80

  php:
    build:
      context: docker/php
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www/html/

  db:
    image: mysql
    command:
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db:/var/lib/mysql
    ports:
      - 3306:3306

  phpmyadmin:
    image: phpmyadmin
    ports:
      - 8080:80

volumes:
  db: ~
