controllers:
    resource: ../src/Controller/
    type: attribute

search_games:
    path: /games/search
    controller: App\Controller\GameController::searchGames
    methods: ['POST']

search_users:
    path: /users/search
    controller: App\Controller\UserController::searchUsers
    methods: ['POST']
